config/routes.rb
RailsSample::Application.routes.draw do
  resources :users do
    collection do
      get "logout"
    end
  end

  root to: 'users#new'
  match '/auth/:provider/callback', to: 'users#create'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :clef_id, :email

  def self.find_or_create_from_auth_hash(auth_hash)
    if user = User.find_by_clef_id(auth_hash[:uid])
        user
    else
        User.create(
            clef_id: auth_hash[:uid],
            email: auth_hash[:info][:email]
        )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :check_user, only: [:new]
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    p request.env['omniauth.auth']
    @user = User.find_or_create_from_auth_hash(request.env['omniauth.auth'])

    respond_to do |format|
      if @user.save
        if @user.persisted?
          notice = "User was logged in."
        else
          notice = "User was created."
        end
        session[:user] = @user.id
        format.html { redirect_to @user, notice: notice }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def logout
    session.delete :user
    redirect_to new_user_path
  end

  protected

    def check_user
      if session[:user]
        @user = User.find(session[:user])
        redirect_to user_path(@user) if @user
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsSample</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :clef_id %><br />
    <%= f.number_field :clef_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Clef</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.clef_id %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>
<!-- code doesnt work implement firebase and ruby <p>

<%=base_uri = 'https://bloodg.firebaseio.com/' %>

firebase = Firebase.new(base_uri)

response = firebase.push("todos", { :name => 'Pick the milk', :priority => 1 })
response.success? # => true
response.code # => 200
response.body # => { 'name' => "-INOQPH-aV_psbk3ZXEX" }
response.raw_body # => '{"name":"-INOQPH-aV_psbk3ZXEX"}' </p> -->

app/views/users/new.html.erb
<h1>Sign in with Clef</h1>

<script type='text/javascript' class='clef-button' src='https://clef.io/v2/clef.js' data-app-id='bc7b3e3fa9ac6ad3f97df4bb03a5a0f6' data-redirect-url='http://localhost:3000/auth/clef/callback'></script>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<html>
<head >
	<script type='text/javascript'
	        src='https://cdn.firebase.com/v0/firebase-simple-login.js'>
	</script>
</head>
<body>
<script>
var chatRef = new Firebase('https://bloodg.firebaseio.com/');
var auth = new FirebaseSimpleLogin(bloodg, function(error, user) {
  
auth.login('anonymous');

});
</script>
<p id="notice"><%= notice %></p>




<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Clef:</b>
  <%= @user.clef_id %>
</p>


<!--hidden <%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> | -->
<%= link_to 'Logout', logout_users_path %>
</body>
</html>